/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lapr.project.ui;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import lapr.project.controller.AtribuirCandidaturaController;
import lapr.project.model.CentroExposicoes;
import lapr.project.model.Demonstracao;
import lapr.project.model.Exposicao;
import lapr.project.model.ExposicaoEstadoConflitosAlterados;
import lapr.project.model.Mecanismo;

/**
 *
 * @author grupo18
 */
public class AtribuirCandidaturaUI extends javax.swing.JFrame {

    private CentroExposicoes centro;
    private String username;
    private AtribuirCandidaturaController controller;
    private DefaultComboBoxModel listaExposicoesModel = new DefaultComboBoxModel();
    private DefaultComboBoxModel listaDemonstracoesModel = new DefaultComboBoxModel();

    /**
     * Creates new form AtribuirCandidaturaUI
     */
    public AtribuirCandidaturaUI(CentroExposicoes centro, String username) {
        this.centro = centro;
        this.username = username;
        this.controller = new AtribuirCandidaturaController(centro);
        List<Exposicao> listaExposicoes = controller.getListaExposicoesOrganizador(username);
        for (int i = 0; i < listaExposicoes.size(); i++) {
            listaExposicoesModel.addElement(listaExposicoes.get(i).getTitulo());
        }
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boxExposicoes = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        boxDemonstracoes = new javax.swing.JComboBox();
        botaoAtribuir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        boxExposicoes.setModel(listaExposicoesModel);
        boxExposicoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxExposicoesActionPerformed(evt);
            }
        });

        jLabel1.setText("Selecione a exposição:");

        jLabel2.setText("Caso deseja atribuir candidaturas de demonstrações selecione a demonstração");

        boxDemonstracoes.setModel(listaDemonstracoesModel);

        botaoAtribuir.setText("ATRIBUIR CANDIDATURAS");
        botaoAtribuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtribuirActionPerformed(evt);
            }
        });

        jLabel3.setText("AVISO: Se não tem exposições para selecionar é porque não é organizador de nenhuma");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxExposicoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxDemonstracoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoAtribuir)
                .addGap(233, 233, 233))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(boxExposicoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boxDemonstracoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(botaoAtribuir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxExposicoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxExposicoesActionPerformed
        if (boxExposicoes.getSelectedIndex() >= 0) {
            List<Demonstracao> listaDemonstracoes = controller.
                    getListaDemonstracoes(controller.
                            getListaExposicoesOrganizador(username).
                            get(boxExposicoes.getSelectedIndex()));
            for (int i = 0; i < listaDemonstracoes.size(); i++) {
                listaDemonstracoesModel.addElement(listaDemonstracoes.get(i).getCodigoUnico());
            }
            boxDemonstracoes.setModel(listaDemonstracoesModel);
        }

    }//GEN-LAST:event_boxExposicoesActionPerformed

    private void botaoAtribuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtribuirActionPerformed
        controller.setMecanismo(new Mecanismo());
        controller.registaAtribuicoesCandidatura();
        this.dispose();
    }//GEN-LAST:event_botaoAtribuirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAtribuir;
    private javax.swing.JComboBox boxDemonstracoes;
    private javax.swing.JComboBox boxExposicoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
