package lapr.project.ui;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import lapr.project.controller.CriarDemonstracaoController;
import lapr.project.model.CentroExposicoes;
import lapr.project.model.Exposicao;

/**
 * @author Grupo 18_LAPR2 15-16
 */
public class CriarDemonstracaoUI extends javax.swing.JFrame {

    private final CriarDemonstracaoController criarDemonstracaoController;
    private CentroExposicoes centroExposicoes;
    private String username;
    private DefaultComboBoxModel listaExposicoesModel = new DefaultComboBoxModel();

    /**
     * Creates new form CriarDemonstracaoUI
     */
    public CriarDemonstracaoUI(CentroExposicoes centro, String username) {
        this.centroExposicoes = centro;
        this.username = username;
        criarDemonstracaoController = new CriarDemonstracaoController(centroExposicoes);
        List<Exposicao> listaExposicoes = criarDemonstracaoController.getListaExposicoes(username);
        for (int i = 0; i < listaExposicoes.size(); i++) {
            listaExposicoesModel.addElement(listaExposicoes.get(i).getTitulo());
        }
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        boxExposicoes = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        codigoDemonstracao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaoDemonstracao = new javax.swing.JTextArea();
        botaoDefinirRecursos = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        botaoContinuar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criar demonstração");
        setResizable(false);

        jLabel1.setText("Por favor, selecione uma exposição:");

        boxExposicoes.setModel(listaExposicoesModel);
        boxExposicoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxExposicoesActionPerformed(evt);
            }
        });

        jLabel2.setText("Código único:");

        jLabel3.setText("Descrição:");

        codigoDemonstracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoDemonstracaoActionPerformed(evt);
            }
        });

        descricaoDemonstracao.setColumns(20);
        descricaoDemonstracao.setRows(5);
        jScrollPane1.setViewportView(descricaoDemonstracao);

        botaoDefinirRecursos.setText("Definir recursos");
        botaoDefinirRecursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDefinirRecursosActionPerformed(evt);
            }
        });

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        botaoContinuar.setText("Continuar");
        botaoContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoContinuarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Atenção:");

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("para selecionar pelo facto de não ser organizador.");

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("não pode criar novas demonstrações caso não tenha exposições");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codigoDemonstracao, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(boxExposicoes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoDefinirRecursos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addComponent(botaoCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoContinuar)))
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(boxExposicoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(1, 1, 1)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codigoDemonstracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoDefinirRecursos)
                    .addComponent(botaoCancelar)
                    .addComponent(botaoContinuar))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoContinuarActionPerformed
        criarDemonstracaoController.setDados(codigoDemonstracao.getText(), descricaoDemonstracao.getText());
        String[] respostas = {"Sim", "Não"};
        if (criarDemonstracaoController.getListaRecursosDem().size() > 0) {
            final ImageIcon icon = new ImageIcon("src/main/resources/question.png");
            int confirmDialog = JOptionPane.showOptionDialog(null, "Tem a certeza que pretende criar esta demonstração?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon, respostas, respostas[0]);
            if (confirmDialog == 0) {
                criarDemonstracaoController.registaDemonstracao();
                this.dispose();
            } else {
                final ImageIcon icon2 = new ImageIcon("src/main/resources/error.png");
                JOptionPane.showMessageDialog(null, "Não foi possível registar a demonstração.", "Atenção", JOptionPane.ERROR_MESSAGE, icon2);
            }
        }else{
            final ImageIcon icon2 = new ImageIcon("src/main/resources/error.png");
            JOptionPane.showMessageDialog(null, "Por favor selecione os recursos necessários.", "Atenção", JOptionPane.ERROR_MESSAGE, icon2);
        }
    }//GEN-LAST:event_botaoContinuarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        String[] respostas = {"Sim", "Não"};
        final ImageIcon icon = new ImageIcon("src/main/resources/question.png");
        int confirmDialog = JOptionPane.showOptionDialog(null, "Tem a certeza que pretende cancelar a operação?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon, respostas, respostas[0]);
        if (confirmDialog == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void boxExposicoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxExposicoesActionPerformed
        criarDemonstracaoController.selectExposicao(boxExposicoes.getSelectedIndex());
        criarDemonstracaoController.novaDemonstracao();
    }//GEN-LAST:event_boxExposicoesActionPerformed

    private void codigoDemonstracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoDemonstracaoActionPerformed
        // INPUT DO CÓDIGO ÚNICO
    }//GEN-LAST:event_codigoDemonstracaoActionPerformed

    private void botaoDefinirRecursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDefinirRecursosActionPerformed
        new AdicionarRecursosDemonstracaoUI(centroExposicoes, criarDemonstracaoController).setVisible(true);
    }//GEN-LAST:event_botaoDefinirRecursosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoContinuar;
    private javax.swing.JButton botaoDefinirRecursos;
    private javax.swing.JComboBox<String> boxExposicoes;
    private javax.swing.JTextField codigoDemonstracao;
    private javax.swing.JTextArea descricaoDemonstracao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
