package lapr.project.ui;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import lapr.project.controller.CriarExposicaoController;
import lapr.project.model.CentroExposicoes;

/** @author Grupo 18_LAPR2 15-16 */

public class CriarExposicaoUI extends javax.swing.JFrame {

    /**
     * Creates new form CriarExposicaoUI
     */
    private final CriarExposicaoController criarExposicaoController;
    private CentroExposicoes centroExposicao;
    private String usernameGestor;

    public CriarExposicaoUI(CentroExposicoes centro, String username) {
        this.centroExposicao = centro;
        criarExposicaoController = new CriarExposicaoController(centroExposicao);
        this.usernameGestor = username;
        criarExposicaoController.novaExposicao();
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tituloNovaExposicao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaoNovaExposicao = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        diaInicioNovaExpo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mesInicioNovaExpo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        anoInicioNovaExpo = new javax.swing.JTextField();
        mesFimNovaExpo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        anoFimNovaExpo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        diaFimNovaExpo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        localNovaExposicao = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        mesInicioCandNovaExpo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        anoInicioCandNovaExpo = new javax.swing.JTextField();
        diaInicioCandNovaExpo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        mesFimCandNovaExpo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        anoFimCandNovaExpo = new javax.swing.JTextField();
        diaFimCandNovaExpo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        mesConflitoNovaExpo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        anoConflitoNovaExpo = new javax.swing.JTextField();
        diaConflitoNovaExpo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        botaoDefinirOrganizadores = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        botaoContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criar exposição");
        setResizable(false);

        jLabel1.setText("Título:");

        tituloNovaExposicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloNovaExposicaoActionPerformed(evt);
            }
        });

        jLabel2.setText("Descrição:");

        descricaoNovaExposicao.setColumns(20);
        descricaoNovaExposicao.setRows(5);
        jScrollPane1.setViewportView(descricaoNovaExposicao);

        jLabel3.setText("Data de início:");

        jLabel4.setText("/");

        jLabel5.setText("/");

        jLabel6.setText("/");

        jLabel7.setText("Data de fim:");

        jLabel8.setText("/");

        jLabel9.setText("Local:");

        jLabel10.setText("Período de submissão de candidaturas:");

        jLabel11.setText("/");

        jLabel12.setText("/");

        jLabel13.setText("/");

        jLabel14.setText("/");

        jLabel15.setText("-");

        jLabel16.setText("Data de limite de especificação de conflitos:");

        jLabel17.setText("/");

        jLabel18.setText("/");

        botaoDefinirOrganizadores.setText("Definir organizadores");
        botaoDefinirOrganizadores.setToolTipText("Definir organizadores para esta exposição");
        botaoDefinirOrganizadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDefinirOrganizadoresActionPerformed(evt);
            }
        });

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        botaoContinuar.setText("Continuar");
        botaoContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoDefinirOrganizadores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoContinuar)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(localNovaExposicao))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(diaInicioNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mesInicioNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(anoInicioNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(diaFimNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mesFimNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(anoFimNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tituloNovaExposicao)))
                            .addComponent(jLabel10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(diaInicioCandNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mesInicioCandNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(anoInicioCandNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(diaFimCandNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mesFimCandNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(anoFimCandNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(diaConflitoNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mesConflitoNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(anoConflitoNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(26, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tituloNovaExposicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(localNovaExposicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(diaInicioNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(mesInicioNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(anoInicioNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(diaFimNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(mesFimNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(anoFimNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diaInicioCandNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(mesInicioCandNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(anoInicioCandNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diaFimCandNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(mesFimCandNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(anoFimCandNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(diaConflitoNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(mesConflitoNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(anoConflitoNovaExpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoDefinirOrganizadores)
                    .addComponent(botaoCancelar)
                    .addComponent(botaoContinuar))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        String[] respostas = {"Sim", "Não"};
        final ImageIcon icon = new ImageIcon("src/main/resources/question.png");
        int confirmDialog = JOptionPane.showOptionDialog(null, "Tem a certeza que pretende cancelar a operação?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon, respostas, respostas[0]);
            if (confirmDialog == 0) {
		this.dispose();
            }
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoContinuarActionPerformed

        DateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        Date dataInicioNovaExposicao = null;
        Date dataFimNovaExposicao = null;
        Date dataInicioCand = null;
        Date dataFimCand = null;
        Date dataLimConflitos = null;
        boolean confirma = true;

        try {
            dataInicioNovaExposicao = df.parse(diaInicioNovaExpo.getText() + "-"
                    + mesInicioNovaExpo.getText() + "-" + anoInicioNovaExpo.getText());
        } catch (ParseException exception) {
            final ImageIcon icon1 = new ImageIcon("src/main/resources/error.png");
            JOptionPane.showMessageDialog(null, "Data de início da exposição errada.", "Erro", JOptionPane.ERROR_MESSAGE, icon1);
            confirma = false;
        }
        try {
            dataFimNovaExposicao = df.parse(diaFimNovaExpo.getText() + "-"
                    + mesFimNovaExpo.getText() + "-" + anoFimNovaExpo.getText());
        } catch (ParseException ex) {
            final ImageIcon icon2 = new ImageIcon("src/main/resources/error.png");
            JOptionPane.showMessageDialog(null, "Data de fim da exposição errada.", "Erro", JOptionPane.ERROR_MESSAGE, icon2);
            confirma = false;
        }

        try {
            dataInicioCand = df.parse(diaInicioCandNovaExpo.getText() + "-"
                    + mesInicioCandNovaExpo.getText() + "-"
                    + anoInicioCandNovaExpo.getText());
        } catch (ParseException ex) {
            final ImageIcon icon3 = new ImageIcon("src/main/resources/error.png");
            JOptionPane.showMessageDialog(null, "Data de início do período de submissão de\ncandidaturas à exposição errada.", "Erro", JOptionPane.ERROR_MESSAGE, icon3);
            confirma = false;
        }
        try {
            dataFimCand = df.parse(diaFimCandNovaExpo.getText() + "-"
                    + mesFimCandNovaExpo.getText() + "-"
                    + anoFimCandNovaExpo.getText());
        } catch (ParseException ex) {
            final ImageIcon icon4 = new ImageIcon("src/main/resources/error.png");
            JOptionPane.showMessageDialog(null, "Data de fim do período de submissão de\ncandidaturas à exposição errada.", "Erro", JOptionPane.ERROR_MESSAGE, icon4);
            confirma = false;
        }
        try {
            dataLimConflitos = df.parse(diaConflitoNovaExpo.getText() + "-"
                    + mesConflitoNovaExpo.getText() + "-"
                    + anoConflitoNovaExpo.getText());
        } catch (ParseException ex) {
            final ImageIcon icon5 = new ImageIcon("src/main/resources/error.png");
            JOptionPane.showMessageDialog(null, "Data de limite de conflitos errada.", "Erro", JOptionPane.ERROR_MESSAGE, icon5);
            confirma = false;
        }
        criarExposicaoController.setDados(tituloNovaExposicao.getText(),
                descricaoNovaExposicao.getText(), dataInicioNovaExposicao,
                dataFimNovaExposicao, localNovaExposicao.getText(),
                dataInicioCand, dataFimCand, dataLimConflitos);
        if (confirma) {
            if (criarExposicaoController.getListaOrganizadores().getListaOrganizadores().size() > 1) {

                int confirmDialog = JOptionPane.showConfirmDialog(null, "Tem a certeza "
                        + "que pretende criar esta exposição?", "Confirmação",
                        JOptionPane.YES_NO_OPTION);
                if (confirmDialog == JOptionPane.YES_OPTION) {
                    criarExposicaoController.registaExposicao();
                }
                final ImageIcon icon7 = new ImageIcon("src/main/resources/check.png");
                JOptionPane.showMessageDialog(null, "Exposição criada com sucesso.", "Informação", JOptionPane.ERROR_MESSAGE, icon7);
                this.dispose();
            }else{
                final ImageIcon icon6 = new ImageIcon("src/main/resources/error.png");
                JOptionPane.showMessageDialog(null, "Número de organizadores insuficiente.\nPor favor, verifique se existem pelo menos 2 organizadores.", "Erro", JOptionPane.ERROR_MESSAGE, icon6);
            }
        }
    }//GEN-LAST:event_botaoContinuarActionPerformed

    private void botaoDefinirOrganizadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDefinirOrganizadoresActionPerformed
        new DefinirOrganizadoresUI(centroExposicao, criarExposicaoController, usernameGestor).setVisible(true);
    }//GEN-LAST:event_botaoDefinirOrganizadoresActionPerformed

    private void tituloNovaExposicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloNovaExposicaoActionPerformed
    }//GEN-LAST:event_tituloNovaExposicaoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anoConflitoNovaExpo;
    private javax.swing.JTextField anoFimCandNovaExpo;
    private javax.swing.JTextField anoFimNovaExpo;
    private javax.swing.JTextField anoInicioCandNovaExpo;
    private javax.swing.JTextField anoInicioNovaExpo;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoContinuar;
    private javax.swing.JButton botaoDefinirOrganizadores;
    private javax.swing.JTextArea descricaoNovaExposicao;
    private javax.swing.JTextField diaConflitoNovaExpo;
    private javax.swing.JTextField diaFimCandNovaExpo;
    private javax.swing.JTextField diaFimNovaExpo;
    private javax.swing.JTextField diaInicioCandNovaExpo;
    private javax.swing.JTextField diaInicioNovaExpo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField localNovaExposicao;
    private javax.swing.JTextField mesConflitoNovaExpo;
    private javax.swing.JTextField mesFimCandNovaExpo;
    private javax.swing.JTextField mesFimNovaExpo;
    private javax.swing.JTextField mesInicioCandNovaExpo;
    private javax.swing.JTextField mesInicioNovaExpo;
    private javax.swing.JTextField tituloNovaExposicao;
    // End of variables declaration//GEN-END:variables
}