package lapr.project.ui;

import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import lapr.project.controller.CriarCandidaturaExposicaoController;
import lapr.project.model.CentroExposicoes;
import lapr.project.model.Exposicao;
import lapr.project.model.ListaDemonstracoes;
import lapr.project.model.ListaProdutos;

/** @author Grupo 18_LAPR2 15-16 */

public class CriarCandidaturaExposicaoUI extends javax.swing.JFrame {

    private final CriarCandidaturaExposicaoController controller;
    private CentroExposicoes centro;
    private String username;
    private Exposicao exposicao;
    private DefaultListModel listaProdutosModel = new DefaultListModel();
    private ListaProdutos listaProdutos;
    private ListaDemonstracoes demonstracoesLista;
    private DefaultListModel listaDemonstracoesModel = new DefaultListModel();

    /**
     * Creates new form CriarCandidaturaUI
     */
    public CriarCandidaturaExposicaoUI(CentroExposicoes centro, String username,
            Exposicao exposicao) {
        this.centro = centro;
        this.username = username;
        this.exposicao = exposicao;
        controller = new CriarCandidaturaExposicaoController(centro, username);
        controller.novaCandidatura(exposicao);
        this.listaProdutos = controller.getListaProdutos();
        for (int i = 0; i < listaProdutos.getListaProdutos().size(); i++) {
            this.listaProdutosModel.addElement(listaProdutos.getListaProdutos().
                    get(i).getNomeProduto());

        }
        this.demonstracoesLista = controller.getListaDemonstracoesCandidatura();
        for (int i = 0; i < demonstracoesLista.getListaDemonstracoes().size(); i++) {
            this.listaDemonstracoesModel.addElement(demonstracoesLista.
                    getListaDemonstracoes().get(i)
                    .getCodigoUnico());
        }
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        contactoField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        moradaText = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        areaField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        convitesField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        produtosLista = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaDemonstracoes = new javax.swing.JList<>();
        botaoMaisProdutos = new javax.swing.JButton();
        botaoMenosProdutos = new javax.swing.JButton();
        botaoMaisDemonstracoes = new javax.swing.JButton();
        botaoMenosDemonstracoes = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        keywordsField = new javax.swing.JTextField();
        botaoCancelar = new javax.swing.JButton();
        botaoContinuar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criar candidatura à exposição");
        setResizable(false);

        jLabel1.setText("Nome comercial:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Informações da empresa");

        jLabel4.setText("Contacto:");

        jLabel6.setText("Morada:");

        moradaText.setColumns(20);
        moradaText.setRows(5);
        jScrollPane2.setViewportView(moradaText);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Informações da candidatura");

        jLabel5.setText("Área pretendida:");

        jLabel7.setText("m");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 8)); // NOI18N
        jLabel8.setText("2");

        jLabel9.setText("Nº de convites pretendidos:");

        convitesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convitesFieldActionPerformed(evt);
            }
        });

        produtosLista.setModel(listaProdutosModel);
        jScrollPane1.setViewportView(produtosLista);

        jLabel11.setText("Lista de produtos:");

        jLabel12.setText("Lista de demonstrações:");

        listaDemonstracoes.setModel(listaDemonstracoesModel);
        jScrollPane3.setViewportView(listaDemonstracoes);

        botaoMaisProdutos.setText("+");
        botaoMaisProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMaisProdutosActionPerformed(evt);
            }
        });

        botaoMenosProdutos.setText("-");
        botaoMenosProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenosProdutosActionPerformed(evt);
            }
        });

        botaoMaisDemonstracoes.setText("+");
        botaoMaisDemonstracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMaisDemonstracoesActionPerformed(evt);
            }
        });

        botaoMenosDemonstracoes.setText("-");
        botaoMenosDemonstracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenosDemonstracoesActionPerformed(evt);
            }
        });

        jLabel10.setText("Caracterização da candidatura:");

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        botaoContinuar.setText("Continuar");
        botaoContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoContinuarActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Atenção:");

        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("é necessário introduzir duas ou mais keywords separadas");

        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("por vírgulas.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botaoCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoContinuar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(keywordsField))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(botaoMaisProdutos)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(botaoMenosProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(botaoMaisDemonstracoes)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(botaoMenosDemonstracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(6, 6, 6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(areaField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel8)
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(convitesField)))
                                .addGap(28, 28, 28))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(contactoField, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(contactoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoMaisProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoMenosProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoMaisDemonstracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoMenosDemonstracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(keywordsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(areaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel5)
                        .addComponent(jLabel9)
                        .addComponent(convitesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoContinuar)
                    .addComponent(botaoCancelar))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoMenosProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenosProdutosActionPerformed
        if (produtosLista.getSelectedIndex() >= 0) {
            listaProdutosModel.remove(produtosLista.getSelectedIndex());
            listaProdutos.getListaProdutos().
                    remove(produtosLista.getSelectedIndex());
        }
    }//GEN-LAST:event_botaoMenosProdutosActionPerformed

    private void botaoMenosDemonstracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenosDemonstracoesActionPerformed
        if (listaDemonstracoes.getSelectedIndex() >= 0) {
            listaDemonstracoesModel.remove(listaDemonstracoes.getSelectedIndex());
            demonstracoesLista.getListaDemonstracoes().
                    remove(listaDemonstracoes.getSelectedIndex());
        }
    }//GEN-LAST:event_botaoMenosDemonstracoesActionPerformed

    private void botaoMaisDemonstracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMaisDemonstracoesActionPerformed
        new AdicionarDemonstracoesCandidaturaUI(centro, controller, listaDemonstracoesModel).setVisible(true);
    }//GEN-LAST:event_botaoMaisDemonstracoesActionPerformed

    private void botaoContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoContinuarActionPerformed

        boolean isValid = true;
        if (!(keywordsField.getText().split(" ").length >= 2
                && keywordsField.getText().split(" ").length <= 5)) {
            isValid = false;
        }

        if (convitesField.getText().equals("")) {
            isValid = false;
        }

        if (areaField.getText().equals("")) {
            isValid = false;
        }
        try {
            if (isValid) {
                controller.setDados(nomeField.getText(), moradaText.getText(),
                        contactoField.getText(), Integer.parseInt(areaField.getText()),
                        Integer.parseInt(convitesField.getText()), keywordsField.getText());
                String[] respostas = {"Sim", "Não"};
                final ImageIcon icon = new ImageIcon("src/main/resources/question.png");
                int confirmDialog = JOptionPane.showOptionDialog(null, "Tem a "
                        + "certeza que deseja criar a candidatura?", "Atenção",
                        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
                        icon, respostas, respostas[0]);
                if (confirmDialog == 0) {
                    controller.registaCandidatura();
                    final ImageIcon icon1 = new ImageIcon("src/main/resources/check.png");
                    JOptionPane.showMessageDialog(null, "Candidatura registada com sucesso.", "Informação", JOptionPane.ERROR_MESSAGE, icon1);
                    this.dispose();
                }
            } else {
                final ImageIcon icon2 = new ImageIcon("src/main/resources/error.png");
                JOptionPane.showMessageDialog(null, "Necessita de criar duas ou mais.", "Erro", JOptionPane.ERROR_MESSAGE, icon2);
            }
        } catch (Exception e) {
            final ImageIcon icon3 = new ImageIcon("src/main/resources/error.png");
            JOptionPane.showMessageDialog(null, "Impossível de criar a "
                    + "candidatura.\nPor favor, verifique as keywords e verifique se "
                    + "introduziu\n corretamente a área e o número de convites.", "Erro", JOptionPane.ERROR_MESSAGE, icon3);
        }
    }//GEN-LAST:event_botaoContinuarActionPerformed

    private void botaoMaisProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMaisProdutosActionPerformed
        new AdicionarProdutosCandidaturaUI(centro, controller, listaProdutosModel).setVisible(true);
    }//GEN-LAST:event_botaoMaisProdutosActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        String[] respostas = {"Sim", "Não"};
        final ImageIcon icon = new ImageIcon("src/main/resources/question.png");
        int confirmDialog = JOptionPane.showOptionDialog(null, "Tem a certeza "
                + "que deseja terminar operação?", "Atenção",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,
                icon, respostas, respostas[0]);
        if (confirmDialog == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void convitesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convitesFieldActionPerformed
        // INPUT ONLY
    }//GEN-LAST:event_convitesFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areaField;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoContinuar;
    private javax.swing.JButton botaoMaisDemonstracoes;
    private javax.swing.JButton botaoMaisProdutos;
    private javax.swing.JButton botaoMenosDemonstracoes;
    private javax.swing.JButton botaoMenosProdutos;
    private javax.swing.JTextField contactoField;
    private javax.swing.JTextField convitesField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField keywordsField;
    private javax.swing.JList<String> listaDemonstracoes;
    private javax.swing.JTextArea moradaText;
    private javax.swing.JTextField nomeField;
    private javax.swing.JList<String> produtosLista;
    // End of variables declaration//GEN-END:variables
}