package lapr.project.ui;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import lapr.project.controller.RemoverCandidaturaController;
import lapr.project.model.CentroExposicoes;
import lapr.project.model.Demonstracao;
import lapr.project.model.Exposicao;
import lapr.project.model.ExposicaoEstado;
import lapr.project.model.ExposicaoEstadoCandidaturasExposicaoFechadas;

/** @author Grupo 18_LAPR2 15-16 */

public class RemoverCandidaturaUI extends javax.swing.JFrame {

    private CentroExposicoes centroExposicoes;
    private RemoverCandidaturaController rcctrl;
    private String idRepresentante;
    private DefaultComboBoxModel listaExposicoesModel;
    private DefaultComboBoxModel listaDemonstracoesModel;

    /**
     * Creates new form RemoverCandidaturaUI
     */
    public RemoverCandidaturaUI(CentroExposicoes centroExposicoes, String id) {
        this.centroExposicoes = centroExposicoes;
        this.idRepresentante = id;
        this.rcctrl = new RemoverCandidaturaController(centroExposicoes, idRepresentante);
        listaExposicoesModel = new DefaultComboBoxModel();
        listaDemonstracoesModel = new DefaultComboBoxModel();
        List<Exposicao> listaExposicoes = rcctrl.getListaExposicoes();
        for (int i = 0; i < listaExposicoes.size(); i++) {
            listaExposicoesModel.addElement(listaExposicoes.get(i).getTitulo());
        }
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exposicaoLabel = new javax.swing.JLabel();
        boxExposicao = new javax.swing.JComboBox<>();
        botaoContinuar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();
        demonstracaoLabel = new javax.swing.JLabel();
        boxDemonstracao = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        infoCandidaturaLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoCandidaturaField = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Remover candidatura");
        setBackground(new java.awt.Color(187, 187, 187));
        setResizable(false);

        exposicaoLabel.setText("Por favor, selecione a exposição:");

        boxExposicao.setModel(listaExposicoesModel);
        boxExposicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxExposicaoActionPerformed(evt);
            }
        });

        botaoContinuar.setText("Continuar");
        botaoContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoContinuarActionPerformed(evt);
            }
        });

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        demonstracaoLabel.setText("Por favor, selecione a demonstração:");
        demonstracaoLabel.setEnabled(false);

        boxDemonstracao.setModel(listaDemonstracoesModel);
        boxDemonstracao.setEnabled(false);
        boxDemonstracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxDemonstracaoActionPerformed(evt);
            }
        });

        infoCandidaturaLabel.setText("Informação da candidatura:");
        infoCandidaturaLabel.setEnabled(false);

        jScrollPane1.setEnabled(false);

        infoCandidaturaField.setEditable(false);
        infoCandidaturaField.setColumns(20);
        infoCandidaturaField.setRows(5);
        jScrollPane1.setViewportView(infoCandidaturaField);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Atenção:");

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("caso pretenda alterar uma candidatura à demonstração, o sistema");

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("automaticamente irá desbloquear os os campos necessários.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(botaoCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoContinuar)
                                .addGap(15, 15, 15))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(boxDemonstracao, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boxExposicao, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(demonstracaoLabel)
                                    .addComponent(exposicaoLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel3)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(infoCandidaturaLabel)))
                        .addGap(0, 51, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exposicaoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boxExposicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(demonstracaoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boxDemonstracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(infoCandidaturaLabel)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoContinuar)
                    .addComponent(botaoCancelar))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoContinuarActionPerformed
        String[] respostas = {"Sim", "Não"};
        final ImageIcon icon = new ImageIcon("src/main/resources/question.png");
        int confirmDialog = JOptionPane.showOptionDialog(null, "Tem a certeza que pretende remover a candidatura selecionada?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon, respostas, respostas[0]);
        if (confirmDialog == 0) {
            rcctrl.removerCandidatura();
            final ImageIcon icon2 = new ImageIcon("src/main/resources/check.png");
            JOptionPane.showMessageDialog(null, "Candidatura removida com sucesso.", "Informação", JOptionPane.ERROR_MESSAGE, icon2);
            this.dispose();
        }
    }//GEN-LAST:event_botaoContinuarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        String[] respostas = {"Sim", "Não"};
        final ImageIcon icon = new ImageIcon("src/main/resources/question.png");
        int confirmDialog = JOptionPane.showOptionDialog(null, "Tem a certeza que pretende cancelar a operação?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon, respostas, respostas[0]);
        if (confirmDialog == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void boxExposicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxExposicaoActionPerformed
        ExposicaoEstado estado = rcctrl.selectExposicao(boxExposicao.getSelectedIndex());
        if (estado instanceof ExposicaoEstadoCandidaturasExposicaoFechadas) {
            demonstracaoLabel.setEnabled(true);
            boxDemonstracao.setEnabled(true);

            List<Demonstracao> listaDemonstracoes = rcctrl.getListaDemonstracoes();
            for (int i = 0; i < 10; i++) {
                listaDemonstracoesModel.addElement(listaDemonstracoes.get(i).getDescricao());
            }
        } else {
            try {
                infoCandidaturaLabel.setEnabled(true);
                infoCandidaturaField.setEnabled(true);
                infoCandidaturaField.setText(rcctrl.getCandidaturaExposicaoRepresentante());
            } catch (NullPointerException exp) {
                final ImageIcon icon = new ImageIcon("src/main/resources/error.png");
                JOptionPane.showMessageDialog(null, "Não possui candidaturas submetidas para esta exposição", "Erro", JOptionPane.ERROR_MESSAGE, icon);
            }
        }
    }//GEN-LAST:event_boxExposicaoActionPerformed

    private void boxDemonstracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxDemonstracaoActionPerformed
        rcctrl.selectDemonstracao(boxDemonstracao.getSelectedIndex());
        try {
            infoCandidaturaLabel.setEnabled(true);
            infoCandidaturaField.setEnabled(true);
            infoCandidaturaField.setText(rcctrl.getCandidaturaDemonstracaoRepresentante());
        } catch (NullPointerException exp) {
            final ImageIcon icon = new ImageIcon("src/main/resources/error.png");
            JOptionPane.showMessageDialog(null, "Não possui candidaturas submetidas para esta demonstração", "Erro", JOptionPane.ERROR_MESSAGE, icon);
        }
    }//GEN-LAST:event_boxDemonstracaoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoContinuar;
    private javax.swing.JComboBox<String> boxDemonstracao;
    private javax.swing.JComboBox<String> boxExposicao;
    private javax.swing.JLabel demonstracaoLabel;
    private javax.swing.JLabel exposicaoLabel;
    private javax.swing.JTextArea infoCandidaturaField;
    private javax.swing.JLabel infoCandidaturaLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}