package lapr.project.ui;

import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import lapr.project.controller.AlterarCandidaturaController;
import lapr.project.model.CentroExposicoes;
import lapr.project.model.ExposicaoEstado;
import lapr.project.model.ExposicaoEstadoCandidaturasExposicaoFechadas;

/**
 * @author Grupo 18_LAPR2 15-16
 */
public class SelecionarCandidaturaAlteracaoCandidaturaUI extends javax.swing.JFrame {

    private CentroExposicoes centroExposicoes;
    private AlterarCandidaturaController acctrl;
    private String idRepresentante;
    private ExposicaoEstado estado;
    private DefaultComboBoxModel listaExposicoesModel = new DefaultComboBoxModel();
    private DefaultComboBoxModel listaDemonstracoesModel = new DefaultComboBoxModel();

    /**
     * Creates new form SelecionarExposicaoAlteracaoCandidaturaUI
     */
    public SelecionarCandidaturaAlteracaoCandidaturaUI(CentroExposicoes centro, String id) {
        this.centroExposicoes = centro;
        this.idRepresentante = id;
        this.acctrl = new AlterarCandidaturaController(centroExposicoes, idRepresentante);
        for (int i = 0; i < acctrl.getListaExposicoes().size(); i++) {
            listaExposicoesModel.addElement(acctrl.getListaExposicoes().get(i).getTitulo());
        }
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        exposicoesComboBox = new javax.swing.JComboBox<>();
        continuarButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        demonstracaoLabel = new javax.swing.JLabel();
        demonstracoesComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar candidatura");
        setResizable(false);

        jLabel1.setText("Por favor, selecione uma exposição:");

        exposicoesComboBox.setModel(listaExposicoesModel);
        exposicoesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exposicoesComboBoxActionPerformed(evt);
            }
        });

        continuarButton.setText("Continuar");
        continuarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        demonstracaoLabel.setText("Por favor, selecione uma demonstração:");
        demonstracaoLabel.setEnabled(false);

        demonstracoesComboBox.setModel(listaDemonstracoesModel);
        demonstracoesComboBox.setEnabled(false);
        demonstracoesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demonstracoesComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Caso pretenda alterar uma candidatura a demonstração,");

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText(" o sistema automaticamente irá desbloquear os campos necessários.");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Aviso:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(continuarButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel1)
                                    .addComponent(demonstracaoLabel)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(demonstracoesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(exposicoesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exposicoesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(demonstracaoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(demonstracoesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continuarButton)
                    .addComponent(cancelarButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continuarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarButtonActionPerformed
        boolean flag = false;
        if (estado instanceof ExposicaoEstadoCandidaturasExposicaoFechadas) {
            try {
                String infoCandidatura = acctrl.getCandidaturaDemonstracaoRepresentante();
            } catch (NullPointerException ep) {
                final ImageIcon icon2 = new ImageIcon("src/main/resources/error.png");
                JOptionPane.showMessageDialog(null, "Não possui candidaturas submetidas para esta demonstração", "Atenção", JOptionPane.ERROR_MESSAGE, icon2);
                this.dispose();
                flag = true;
            }
            if (flag == false) {
                new AlterarCandidaturaDemonstracaoUI(centroExposicoes, acctrl, idRepresentante).setVisible(true);
                this.dispose();
            }
        } else {
            try {
                String[] infoCandidatura = acctrl.getCandidaturaExposicaoRepresentante();
            } catch (NullPointerException ep) {
                final ImageIcon icon2 = new ImageIcon("src/main/resources/error.png");
                JOptionPane.showMessageDialog(null, "Não possui candidaturas submetidas para esta exposição", "Atenção", JOptionPane.ERROR_MESSAGE, icon2);
                flag = true;
            }
            if (flag == false) {
                new AlterarCandidaturaExposicaoUI(centroExposicoes, acctrl, idRepresentante).setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_continuarButtonActionPerformed

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        String[] respostas = {"Sim", "Não"};
        final ImageIcon icon = new ImageIcon("src/main/resources/question.png");
        int confirmDialog = JOptionPane.showOptionDialog(null, "Tem a certeza que pretende cancelar a operação?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, icon, respostas, respostas[0]);
        if (confirmDialog == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void exposicoesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exposicoesComboBoxActionPerformed
        if (acctrl.selectExposicao(exposicoesComboBox.getSelectedIndex()) instanceof ExposicaoEstadoCandidaturasExposicaoFechadas) {
            demonstracaoLabel.setEnabled(true);
            demonstracoesComboBox.setEnabled(true);

        }
    }//GEN-LAST:event_exposicoesComboBoxActionPerformed

    private void demonstracoesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demonstracoesComboBoxActionPerformed
        acctrl.selectDemonstracao(demonstracoesComboBox.getSelectedIndex());
    }//GEN-LAST:event_demonstracoesComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarButton;
    private javax.swing.JButton continuarButton;
    private javax.swing.JLabel demonstracaoLabel;
    private javax.swing.JComboBox<String> demonstracoesComboBox;
    private javax.swing.JComboBox<String> exposicoesComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
