package ems.gui;
// STATUS: DONE
// ISSUES: NONE

import ems.controller.ApplyToEventController;
import ems.model.Event;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Panel that allows input of a new application to event.
 * @author 1DK_1150475_1161975_1161976
 */
public class ApplyToEventPanel extends javax.swing.JPanel {
    
    // Class variables
    private final ApplicationsPanel applicationsPanel;
    private final ApplyToEventController applyToEventController;
    private static final ImageIcon QUESTION_ICON = new ImageIcon("src/ems/assets/question.png");
    private static final ImageIcon ERROR_ICON = new ImageIcon("src/ems/assets/error.png");
    private static final ImageIcon CHECK_ICON = new ImageIcon("src/ems/assets/check.png");
    
    /**
     * Creates new form of applyToExpo UI.
     * @param applicationsPanel
     */
    public ApplyToEventPanel(ApplicationsPanel applicationsPanel) {
        this.applicationsPanel = applicationsPanel;
        this.applyToEventController = new ApplyToEventController(applicationsPanel.getActiveEMS().getActiveFairCenter());
        initComponents();
        representativeLabel.setText(applyToEventController.getRepresentative().getName());
        getEventsToComboBox();
        updateSelectedEventInfo();
    }
    
    private void getEventsToComboBox(){
        for(int i = 0; i<applicationsPanel.getActiveEMS().getActiveFairCenter().getEventRegistry().getEventList().size(); i++){
            eventComboBox.addItem(applicationsPanel.getActiveEMS().getActiveFairCenter().getEventRegistry().getEventList().get(i).getTitle());
        }
    }
    
    private void updateSelectedEventInfo(){
        eventComboBox.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                Event eventAux = getSelectedEvent();
                applyToEventController.setActiveEvent(eventAux);
                startDateLabel.setText(eventAux.getStartDate().toAnoMesDiaString());
                endDateLabel.setText(eventAux.getEndDate().toAnoMesDiaString());
                eventDescriptionTextArea.setText("ID #" +eventAux.getEventID() +"\n" +eventAux.getDescription());
            }
        
        });
    }
    
    private Event getSelectedEvent(){
        String titleAux = eventComboBox.getSelectedItem().toString();
        for(int i = 0; i<applicationsPanel.getActiveEMS().getActiveFairCenter().getEventRegistry().getEventList().size(); i++){
            if(titleAux.equalsIgnoreCase(applicationsPanel.getActiveEMS().getActiveFairCenter().getEventRegistry().getEventList().get(i).getTitle())){
                return applicationsPanel.getActiveEMS().getActiveFairCenter().getEventRegistry().getEventList().get(i);
            } else return null;
        }
        return null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        goBackButton = new javax.swing.JLabel();
        currentTaskLabel = new javax.swing.JLabel();
        submitLabel = new javax.swing.JLabel();
        eraseLabel = new javax.swing.JLabel();
        eventSelectionPanel = new javax.swing.JPanel();
        eventComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        startDateLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        endDateLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        eventDescriptionTextArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        companyNameTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        companyAddressTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        phoneNumberTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        representativeLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionTextArea = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        pretendedAreaTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        invitesNumberTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        goBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems/assets/back.png"))); // NOI18N
        goBackButton.setToolTipText("Cancel and go back");
        goBackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goBackButtonMouseClicked(evt);
            }
        });

        currentTaskLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        currentTaskLabel.setForeground(new java.awt.Color(255, 255, 255));
        currentTaskLabel.setText("Apply to active event");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(goBackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(currentTaskLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(goBackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(currentTaskLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        submitLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        submitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems/assets/submit.png"))); // NOI18N
        submitLabel.setText("Submit application");
        submitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        submitLabel.setIconTextGap(8);
        submitLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        submitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitLabelMouseClicked(evt);
            }
        });

        eraseLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        eraseLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems/assets/erase.png"))); // NOI18N
        eraseLabel.setText("Erase all fields");
        eraseLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eraseLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eraseLabel.setIconTextGap(8);
        eraseLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        eraseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eraseLabelMouseClicked(evt);
            }
        });

        eventSelectionPanel.setBackground(new java.awt.Color(255, 255, 255));
        eventSelectionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Event selection"));

        jLabel1.setText("Apply to");
        jLabel1.setEnabled(false);

        jLabel2.setText("from");
        jLabel2.setEnabled(false);

        startDateLabel.setText("--/--/----");

        jLabel4.setText("to");
        jLabel4.setEnabled(false);

        endDateLabel.setText("--/--/----");

        jLabel3.setText("About this event:");
        jLabel3.setEnabled(false);

        eventDescriptionTextArea.setEditable(false);
        eventDescriptionTextArea.setColumns(20);
        eventDescriptionTextArea.setRows(5);
        eventDescriptionTextArea.setEnabled(false);
        jScrollPane1.setViewportView(eventDescriptionTextArea);

        javax.swing.GroupLayout eventSelectionPanelLayout = new javax.swing.GroupLayout(eventSelectionPanel);
        eventSelectionPanel.setLayout(eventSelectionPanelLayout);
        eventSelectionPanelLayout.setHorizontalGroup(
            eventSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventSelectionPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eventComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startDateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endDateLabel)
                .addGap(26, 26, 26)
                .addGroup(eventSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eventSelectionPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(100, 100, 100))
        );
        eventSelectionPanelLayout.setVerticalGroup(
            eventSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventSelectionPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(eventSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eventComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Submission details"));

        jLabel5.setText("Company name:");

        jLabel6.setText("Company address:");

        jLabel7.setText("Phone number:");

        jLabel8.setText("Representative:");

        representativeLabel.setText("John Doe");
        representativeLabel.setToolTipText("To change this, sign in as another representative.");
        representativeLabel.setEnabled(false);

        jLabel10.setText("Description and company goals:");

        descriptionTextArea.setColumns(20);
        descriptionTextArea.setRows(5);
        jScrollPane2.setViewportView(descriptionTextArea);

        jLabel12.setText("Pretended area:");

        jLabel9.setText("m2");
        jLabel9.setEnabled(false);

        jLabel13.setText("Number of invites wanted:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(representativeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phoneNumberTextField))
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(companyNameTextField)
                    .addComponent(companyAddressTextField))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pretendedAreaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel9)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(invitesNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(companyNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(companyAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(representativeLabel)
                    .addComponent(jLabel12)
                    .addComponent(pretendedAreaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(invitesNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 627, Short.MAX_VALUE)
                        .addComponent(eraseLabel)
                        .addGap(38, 38, 38)
                        .addComponent(submitLabel))
                    .addComponent(eventSelectionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 908, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 908, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(eventSelectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitLabel)
                    .addComponent(eraseLabel))
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void goBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goBackButtonMouseClicked
        String[] answers = {"No", "Yes"};
            int confirmDialog = JOptionPane.showOptionDialog(null, "Are you sure you want to cancel and go back?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, QUESTION_ICON, answers, answers[0]);
                if (confirmDialog == 1) {
                    applicationsPanel.goBackToApplicationsPanel();
                }
    }//GEN-LAST:event_goBackButtonMouseClicked

    private void eraseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eraseLabelMouseClicked
        String[] answers = {"No", "Yes"};
            int confirmDialog = JOptionPane.showOptionDialog(null, "Are you sure you want to erase all submission fields?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, QUESTION_ICON, answers, answers[0]);
                if (confirmDialog == 1) {
                    companyNameTextField.setText("");
                    companyAddressTextField.setText("");
                    phoneNumberTextField.setText("");
                    descriptionTextArea.setText("");
                    pretendedAreaTextField.setText("");
                    invitesNumberTextField.setText("");
                    invitesNumberTextField.transferFocus();
                }
    }//GEN-LAST:event_eraseLabelMouseClicked

    private void submitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitLabelMouseClicked
        String[] answers = {"No", "Yes"};
            int confirmDialog = JOptionPane.showOptionDialog(null, "Are you sure you want to submit this?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, QUESTION_ICON, answers, answers[0]);
                if (confirmDialog == 1) {
                    try {
                        try {
                            if(phoneNumberTextField.getText().length() > 14 || phoneNumberTextField.getText().length() < 9){
                                throw new NumberFormatException("Phone number is invalid!");
                            } else {
                                applyToEventController.submitEventApplication(companyNameTextField.getText(), companyAddressTextField.getText(), descriptionTextArea.getText(), Integer.valueOf(phoneNumberTextField.getText()), Integer.valueOf(pretendedAreaTextField.getText()), Integer.valueOf(invitesNumberTextField.getText()));
                            }
                        } catch (IOException ex) {
                            Logger.getLogger(ApplyToEventPanel.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        JOptionPane.showMessageDialog(null, "Application submitted successfully.", "Notification", JOptionPane.ERROR_MESSAGE, CHECK_ICON);
                        applicationsPanel.goBackToApplicationsPanel();
                    } catch(NumberFormatException nfe) {
                        JOptionPane.showMessageDialog(null, "One or more fields have invalid input!\nPlease verify your submission.", "Error", JOptionPane.ERROR_MESSAGE, ERROR_ICON);
                    }
                }
    }//GEN-LAST:event_submitLabelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField companyAddressTextField;
    private javax.swing.JTextField companyNameTextField;
    private javax.swing.JLabel currentTaskLabel;
    private javax.swing.JTextArea descriptionTextArea;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JLabel eraseLabel;
    private javax.swing.JComboBox<String> eventComboBox;
    private javax.swing.JTextArea eventDescriptionTextArea;
    private javax.swing.JPanel eventSelectionPanel;
    private javax.swing.JLabel goBackButton;
    private javax.swing.JTextField invitesNumberTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JTextField pretendedAreaTextField;
    private javax.swing.JLabel representativeLabel;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JLabel submitLabel;
    // End of variables declaration//GEN-END:variables
}