package ems.gui;
// STATUS: DONE
// ISSUES: NONE

import ems.model.FairCenter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import ems.controller.DashboardController;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * JFrame that allows to modify the center info
 * @author 1DK_1150475_1161975_1161976
 */
public class CenterInfoUI extends javax.swing.JFrame {
    
    // Class variables
    private final EMS ems;
    private final FairCenter fairCenter;
    private final DashboardController dashboardController;
    private static final ImageIcon QUESTION_ICON = new ImageIcon("src/ems/assets/question.png");
    private static final ImageIcon CHECK_ICON = new ImageIcon("src/ems/assets/check.png");
    
    /**
     * Creates new form centerInfoUI
     * @param ems
     * @param fairCenter
     */
    public CenterInfoUI(EMS ems, FairCenter fairCenter) {
        this.ems = ems;
        this.fairCenter = fairCenter;
        this.dashboardController = new DashboardController(fairCenter);
        initComponents();
        cancelButton.requestFocus();
        centerNameField.setText(dashboardController.updateCenterName());
        centerAddressField.setText(dashboardController.updateCenterAddress());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        centerNameLabel = new javax.swing.JLabel();
        centerAddressLabel = new javax.swing.JLabel();
        centerNameField = new javax.swing.JTextField();
        centerAddressField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Center information");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        centerNameLabel.setText("Name:");

        centerAddressLabel.setText("Address:");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(saveButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cancelButton))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(centerAddressLabel)
                            .addComponent(centerAddressField)
                            .addComponent(centerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(centerNameLabel))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(centerNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(centerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(centerAddressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(centerAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String[] answers = {"No", "Yes"};
        int confirmDialog = JOptionPane.showOptionDialog(null, "Save changes?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, QUESTION_ICON, answers, answers[0]);
            if (confirmDialog == 1) {
                String nameAux = centerNameField.getText();
                String addressAux = centerAddressField.getText();
            try {
                dashboardController.setNewCenterInfo(nameAux, addressAux);
            } catch (IOException ex) {
                Logger.getLogger(CenterInfoUI.class.getName()).log(Level.SEVERE, null, ex);
            }
                this.dispose();
                JOptionPane.showMessageDialog(null, "Changes saved successfully.", "Notification", JOptionPane.ERROR_MESSAGE, CHECK_ICON);
                DashboardPanel dashboardPanelAux = (DashboardPanel) ems.getDashboardPanel();
                dashboardPanelAux.updateDashboardInfo();
            }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField centerAddressField;
    private javax.swing.JLabel centerAddressLabel;
    private javax.swing.JTextField centerNameField;
    private javax.swing.JLabel centerNameLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}