package ems.gui;
// STATUS: DONE
// ISSUES: NONE

import ems.controller.DashboardController;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * Panel with start screen/dashboard.
 * @author 1DK_1150475_1161975_1161976
 */
public class DashboardPanel extends javax.swing.JPanel {

    // Class variables
    private final EMS ems;
    private final DashboardController dashboardController;
    private static final ImageIcon QUESTION_ICON = new ImageIcon("src/ems/assets/question.png");
    private static final ImageIcon CHECK_ICON = new ImageIcon("src/ems/assets/check.png");
    private static final ImageIcon ERROR_ICON = new ImageIcon("src/ems/assets/error.png");
    
    /**
     * Creates a new dashboardPanel
     * @param ems
     */
    public DashboardPanel(EMS ems) {
        this.ems = ems;
        this.dashboardController = new DashboardController(ems.getActiveFairCenter());
        initComponents();
        updateDashboardInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userInfoPanel = new javax.swing.JPanel();
        profilePictureLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        myAccountLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        signoutLabel = new javax.swing.JLabel();
        centerInfoPanel = new javax.swing.JPanel();
        centerPictureLabel = new javax.swing.JLabel();
        centerNameLabel = new javax.swing.JLabel();
        editCenterLabel = new javax.swing.JLabel();
        centerAddressLabel = new javax.swing.JLabel();
        statusOverviewPanel = new javax.swing.JPanel();
        numberExposLabel = new javax.swing.JLabel();
        expositionsElement = new javax.swing.JLabel();
        numberAppLabel = new javax.swing.JLabel();
        unreadElement = new javax.swing.JLabel();
        numberStandsLabel = new javax.swing.JLabel();
        activeElement = new javax.swing.JLabel();
        scheduledElement = new javax.swing.JLabel();
        applicationsElement = new javax.swing.JLabel();
        standsElement = new javax.swing.JLabel();
        numberConflictsLabel = new javax.swing.JLabel();
        conflictsElement = new javax.swing.JLabel();
        detectedElement = new javax.swing.JLabel();
        numberUsersLabel = new javax.swing.JLabel();
        registeredElement = new javax.swing.JLabel();
        usersElement = new javax.swing.JLabel();
        cloudSyncElement = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        userInfoPanel.setBackground(new java.awt.Color(255, 255, 255));
        userInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        profilePictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems/assets/user.png"))); // NOI18N

        welcomeLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        welcomeLabel.setText("Welcome Administrator");

        myAccountLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        myAccountLabel.setForeground(new java.awt.Color(33, 113, 216));
        myAccountLabel.setText("My account");
        myAccountLabel.setToolTipText("View and edit your employee/account information");
        myAccountLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        myAccountLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myAccountLabelMouseClicked(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(102, 102, 102));
        emailLabel.setText("admin@ems.com");
        emailLabel.setToolTipText("Your e-mail address");

        signoutLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        signoutLabel.setForeground(new java.awt.Color(33, 113, 216));
        signoutLabel.setText("Sign out");
        signoutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signoutLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout userInfoPanelLayout = new javax.swing.GroupLayout(userInfoPanel);
        userInfoPanel.setLayout(userInfoPanelLayout);
        userInfoPanelLayout.setHorizontalGroup(
            userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(profilePictureLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userInfoPanelLayout.createSequentialGroup()
                        .addComponent(myAccountLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(signoutLabel))
                    .addGroup(userInfoPanelLayout.createSequentialGroup()
                        .addComponent(welcomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailLabel)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        userInfoPanelLayout.setVerticalGroup(
            userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profilePictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userInfoPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcomeLabel)
                    .addComponent(emailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myAccountLabel)
                    .addComponent(signoutLabel))
                .addGap(30, 30, 30))
        );

        centerInfoPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Center information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        centerPictureLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems/assets/center.png"))); // NOI18N

        centerNameLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        centerNameLabel.setText("Exposition Hall");
        centerNameLabel.setToolTipText("Center's name");

        editCenterLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        editCenterLabel.setForeground(new java.awt.Color(33, 113, 216));
        editCenterLabel.setText("Edit");
        editCenterLabel.setToolTipText("Edit current center's information");
        editCenterLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editCenterLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editCenterLabelMouseClicked(evt);
            }
        });

        centerAddressLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        centerAddressLabel.setForeground(new java.awt.Color(102, 102, 102));
        centerAddressLabel.setText("North Avenue, 123");
        centerAddressLabel.setToolTipText("Center's address");

        javax.swing.GroupLayout centerInfoPanelLayout = new javax.swing.GroupLayout(centerInfoPanel);
        centerInfoPanel.setLayout(centerInfoPanelLayout);
        centerInfoPanelLayout.setHorizontalGroup(
            centerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerInfoPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(centerPictureLabel)
                .addGap(14, 14, 14)
                .addGroup(centerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(centerInfoPanelLayout.createSequentialGroup()
                        .addComponent(centerNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(centerAddressLabel))
                    .addComponent(editCenterLabel))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        centerInfoPanelLayout.setVerticalGroup(
            centerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(centerPictureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerInfoPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(centerInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(centerNameLabel)
                    .addComponent(centerAddressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editCenterLabel)
                .addGap(30, 30, 30))
        );

        statusOverviewPanel.setBackground(new java.awt.Color(255, 255, 255));
        statusOverviewPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Status overview", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        numberExposLabel.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        numberExposLabel.setForeground(new java.awt.Color(33, 113, 216));
        numberExposLabel.setText("0");

        expositionsElement.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        expositionsElement.setText("events");

        numberAppLabel.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        numberAppLabel.setText("-");
        numberAppLabel.setEnabled(false);

        unreadElement.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        unreadElement.setText("unread");
        unreadElement.setEnabled(false);

        numberStandsLabel.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        numberStandsLabel.setText("-");
        numberStandsLabel.setEnabled(false);

        activeElement.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        activeElement.setText("active");
        activeElement.setEnabled(false);

        scheduledElement.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        scheduledElement.setText("scheduled");

        applicationsElement.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        applicationsElement.setText("applications");
        applicationsElement.setEnabled(false);

        standsElement.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        standsElement.setText("stands");
        standsElement.setEnabled(false);

        numberConflictsLabel.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        numberConflictsLabel.setText("-");
        numberConflictsLabel.setEnabled(false);

        conflictsElement.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        conflictsElement.setText("conflicts");
        conflictsElement.setEnabled(false);

        detectedElement.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        detectedElement.setText("detected");
        detectedElement.setEnabled(false);

        numberUsersLabel.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        numberUsersLabel.setForeground(new java.awt.Color(33, 113, 216));
        numberUsersLabel.setText("0");

        registeredElement.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        registeredElement.setText("registered");

        usersElement.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        usersElement.setText("users");

        cloudSyncElement.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cloudSyncElement.setForeground(new java.awt.Color(102, 102, 102));
        cloudSyncElement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems/assets/cloud-error.png"))); // NOI18N
        cloudSyncElement.setText(" Cloud sync unavailable! Database will be stored locally.");
        cloudSyncElement.setToolTipText("Contact your system administrator to set up this feature");

        javax.swing.GroupLayout statusOverviewPanelLayout = new javax.swing.GroupLayout(statusOverviewPanel);
        statusOverviewPanel.setLayout(statusOverviewPanelLayout);
        statusOverviewPanelLayout.setHorizontalGroup(
            statusOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusOverviewPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(statusOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cloudSyncElement)
                    .addGroup(statusOverviewPanelLayout.createSequentialGroup()
                        .addGroup(statusOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(expositionsElement)
                            .addComponent(numberExposLabel)
                            .addComponent(scheduledElement))
                        .addGap(40, 40, 40)
                        .addGroup(statusOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unreadElement)
                            .addComponent(numberAppLabel)
                            .addComponent(applicationsElement))
                        .addGap(40, 40, 40)
                        .addGroup(statusOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(standsElement)
                            .addComponent(activeElement)
                            .addComponent(numberStandsLabel))
                        .addGap(40, 40, 40)
                        .addGroup(statusOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(detectedElement)
                            .addComponent(conflictsElement)
                            .addComponent(numberConflictsLabel))
                        .addGap(40, 40, 40)
                        .addGroup(statusOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usersElement)
                            .addComponent(registeredElement)
                            .addComponent(numberUsersLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        statusOverviewPanelLayout.setVerticalGroup(
            statusOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusOverviewPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(statusOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(statusOverviewPanelLayout.createSequentialGroup()
                        .addComponent(numberUsersLabel)
                        .addGap(0, 0, 0)
                        .addComponent(registeredElement)
                        .addGap(0, 0, 0)
                        .addComponent(usersElement))
                    .addGroup(statusOverviewPanelLayout.createSequentialGroup()
                        .addComponent(numberConflictsLabel)
                        .addGap(0, 0, 0)
                        .addComponent(conflictsElement)
                        .addGap(0, 0, 0)
                        .addComponent(detectedElement))
                    .addGroup(statusOverviewPanelLayout.createSequentialGroup()
                        .addGroup(statusOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(statusOverviewPanelLayout.createSequentialGroup()
                                .addGroup(statusOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(numberAppLabel)
                                    .addComponent(numberStandsLabel))
                                .addGap(0, 0, 0)
                                .addGroup(statusOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(unreadElement)
                                    .addComponent(activeElement)))
                            .addGroup(statusOverviewPanelLayout.createSequentialGroup()
                                .addComponent(numberExposLabel)
                                .addGap(0, 0, 0)
                                .addComponent(expositionsElement)))
                        .addGroup(statusOverviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scheduledElement)
                            .addComponent(applicationsElement)
                            .addComponent(standsElement))))
                .addGap(36, 36, 36)
                .addComponent(cloudSyncElement)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(statusOverviewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(centerInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(centerInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(statusOverviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void myAccountLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myAccountLabelMouseClicked
        UserAccountUI userProfileUI = new UserAccountUI(ems, ems.getActiveFairCenter());
        userProfileUI.setVisible(true);
    }//GEN-LAST:event_myAccountLabelMouseClicked

    private void editCenterLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editCenterLabelMouseClicked
        CenterInfoUI centerInfoUI = new CenterInfoUI(ems, ems.getActiveFairCenter());
        centerInfoUI.setVisible(true);
    }//GEN-LAST:event_editCenterLabelMouseClicked

    private void signoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signoutLabelMouseClicked
        String[] answers = {"No", "Yes"};
        int confirmDialog = JOptionPane.showOptionDialog(null, "Are you sure you want to sign out?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, QUESTION_ICON, answers, answers[0]);
            if (confirmDialog == 1) {
                ems.dispose();
                dashboardController.endActiveSession();
                ems.reStartApp(ems.getActiveFairCenter());
            }
    }//GEN-LAST:event_signoutLabelMouseClicked
    
    public void updateDashboardInfo(){
        centerNameLabel.setText(dashboardController.updateCenterName());
        centerAddressLabel.setText(dashboardController.updateCenterAddress());
        welcomeLabel.setText("Welcome " + dashboardController.getActiveUserName());
        emailLabel.setText(dashboardController.getActiveUserEmail());
        numberExposLabel.setText(dashboardController.updateEventsScheduled());
        numberUsersLabel.setText(dashboardController.updateUsersRegistered());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activeElement;
    private javax.swing.JLabel applicationsElement;
    private javax.swing.JLabel centerAddressLabel;
    private javax.swing.JPanel centerInfoPanel;
    private javax.swing.JLabel centerNameLabel;
    private javax.swing.JLabel centerPictureLabel;
    private javax.swing.JLabel cloudSyncElement;
    private javax.swing.JLabel conflictsElement;
    private javax.swing.JLabel detectedElement;
    private javax.swing.JLabel editCenterLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel expositionsElement;
    private javax.swing.JLabel myAccountLabel;
    private javax.swing.JLabel numberAppLabel;
    private javax.swing.JLabel numberConflictsLabel;
    private javax.swing.JLabel numberExposLabel;
    private javax.swing.JLabel numberStandsLabel;
    private javax.swing.JLabel numberUsersLabel;
    private javax.swing.JLabel profilePictureLabel;
    private javax.swing.JLabel registeredElement;
    private javax.swing.JLabel scheduledElement;
    private javax.swing.JLabel signoutLabel;
    private javax.swing.JLabel standsElement;
    private javax.swing.JPanel statusOverviewPanel;
    private javax.swing.JLabel unreadElement;
    private javax.swing.JPanel userInfoPanel;
    private javax.swing.JLabel usersElement;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}