package ems.gui;
// STATUS: DONE
// ISSUES: NONE

import ems.model.FairCenter;
import ems.controller.SignInController;
import ems.model.user.User;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 * Allows the user to sign in.
 * @author 1DK_1150475_1161975_1161976
 */
public class SignInUI extends javax.swing.JFrame {

    // Class variables
    private final FairCenter fairCenter;
    private final SignInController signInController;
    private static final Font NULL_FONT_AUX = null;
    private static final ImageIcon ERROR_ICON = new ImageIcon("src/ems/assets/error.png");
    
    /**
     * Creates new LoginUI
     * @param fairCenter
     */
    public SignInUI(FairCenter fairCenter) {
        this.fairCenter = fairCenter;
        this.signInController = new SignInController(fairCenter);
        initComponents();
        getEnterButton().requestFocus();
        this.getRootPane().setDefaultButton(getEnterButton());
    }
    
    public JTextField getEmailTextField() {
        return emailTextField;
    }
    
    public JButton getEnterButton() {
        return enterButton;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        topTitleLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JTextField();
        emailIconLabel = new javax.swing.JLabel();
        passwordIconLabel = new javax.swing.JLabel();
        enterButton = new javax.swing.JButton();
        forgotLabel = new javax.swing.JLabel();
        newUserLabel = new javax.swing.JLabel();
        createAccountLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Event Management System");
        setIconImage(new ImageIcon("src/ems/assets/ems.png").getImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        topTitleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        topTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        topTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topTitleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems/assets/ems-locked.png"))); // NOI18N
        topTitleLabel.setText(" Sign in to EMS");
        topTitleLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        topTitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        topTitleLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        emailTextField.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        emailTextField.setText("e-mail address");
        emailTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailTextFieldMouseClicked(evt);
            }
        });

        passwordTextField.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        passwordTextField.setText("password");
        passwordTextField.setEnabled(false);

        emailIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems/assets/email.png"))); // NOI18N

        passwordIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ems/assets/password.png"))); // NOI18N
        passwordIconLabel.setEnabled(false);

        enterButton.setText("Enter");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        forgotLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        forgotLabel.setForeground(new java.awt.Color(255, 255, 255));
        forgotLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgotLabel.setText(" Forgot your credentials?");
        forgotLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgotLabel.setEnabled(false);

        newUserLabel.setForeground(new java.awt.Color(255, 255, 255));
        newUserLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        newUserLabel.setText("New user?");
        newUserLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        newUserLabel.setEnabled(false);

        createAccountLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        createAccountLabel.setForeground(new java.awt.Color(255, 255, 255));
        createAccountLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        createAccountLabel.setText("Create an account now.");
        createAccountLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createAccountLabel.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(forgotLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(enterButton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(emailIconLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(passwordIconLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(112, 112, 112))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(newUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createAccountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(topTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordIconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(enterButton)
                .addGap(60, 60, 60)
                .addComponent(forgotLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createAccountLabel)
                    .addComponent(newUserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        User userAux = signInController.validateSession(getEmailTextField().getText());
        if(userAux == null){
            JOptionPane.showMessageDialog(null, "Incorrect credentials!\nPlease check your e-mail and password.", "Access denied", JOptionPane.ERROR_MESSAGE, ERROR_ICON);
        } else {
        this.dispose();
        java.awt.EventQueue.invokeLater(() -> {
            new EMS(fairCenter, userAux).setVisible(true);
        });
        }
    }//GEN-LAST:event_enterButtonActionPerformed

    private void emailTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTextFieldMouseClicked
        getEmailTextField().setFont(NULL_FONT_AUX);
        getEmailTextField().setText("");
    }//GEN-LAST:event_emailTextFieldMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel createAccountLabel;
    private javax.swing.JLabel emailIconLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton enterButton;
    private javax.swing.JLabel forgotLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel newUserLabel;
    private javax.swing.JLabel passwordIconLabel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JLabel topTitleLabel;
    // End of variables declaration//GEN-END:variables
}